spring:
    profiles:
        active:
        - dev

---
spring:
    profiles: dev
    application:
        name: micros-dev
        
---
spring:
    profiles: test
    application:
        name: micros-test